### ISSUE TITLE
LEGO Star Wars 2

### ISSUE THREAD

**Issue by dabussy** [jserodio/rg351p-ppsspp-settings#1]
Does anyone have a good setup for LEGO Star Wars 2 The original Trilogy

**Comment by jserodio** [comment]
First tests are unsuccessful...

Almost 60 fps in the lobby. Turning frameskip to 1, makes it go 100% speed, but at 30 fps and with some input lag.
Then going into battle, the game goes at 20-25 fps out of 30 fps. It's unplayable right now.

I'm also facing an issue I never had before on PPSSPP, not sure if it's just me, but I can't save state.
And this is a big deal because whenever I try to change buffer settings, I need to restart the game and can't skip every intro.
I can't quickly test changing the PPSSPP's CPU speed... because I chose to load savestates instead of restarting the game to test CPU speed changes... Etc...

It's a bit sad because the game looks incredible and seems to be very enjoyable at 60 fps.

**Comment by dabussy** [comment]
Thank you so much man I greatly appreciate your time. I also have the same problem but I thought it was because I had no space on my SD card.  Have an amazing day!

**Comment by jserodio** [comment]
Hi man, I'm here to report some good news.

The issue about not saving the game, is just a PPSSPP issue that can be fixed by using a cheat file.
You can read more about this here: [https://forums.ppsspp.org/showthread.php?tid=22787&pid=126016](https://forums.ppsspp.org/showthread.php?tid=22787&pid=126016)

Depending on your gamecode you need one of the following inis.

**ULUS10155.ini**
`_S ULUS-10155
_G LEGO Star Wars II: The Original Trilogy [USA]
_C0 Insufficient free space FIX
_L 0xE0060030 0x0000D190
_L 0x2000D190 0x34040200
_L 0x2000D194 0x34050040
_L 0x2000D198 0x34067999
_L 0x200509CC 0x34040200
_L 0x200509D0 0x34050040
_L 0x200509E4 0x34047999
_C0 Insufficient free space NO-FIX [Default]
_L 0xE0060200 0x0000D190
_L 0x2000D190 0x8FA40030
_L 0x2000D194 0x8FA50034
_L 0x2000D198 0x8FA60028
_L 0x200509CC 0x8FA40030
_L 0x200509D0 0x8FA50034
_L 0x200509E4 0x8FA40028`

**ULES00479.ini**
`_S ULES-00479
_G LEGO Star Wars II: The Original Trilogy [EUR]
_C0 Insufficient free space FIX
_L 0xE0060030 0x0000D358
_L 0x2000D358 0x34040200
_L 0x2000D35C 0x34050040
_L 0x2000D360 0x34067999
_L 0x20050CE8 0x34040200
_L 0x20050CEC 0x34050040
_L 0x20050D00 0x34047999
_C0 Insufficient free space NO-FIX [Default]
_L 0xE0060200 0x0000D358
_L 0x2000D358 0x8FA40030
_L 0x2000D35C 0x8FA50034
_L 0x2000D360 0x8FA60028
_L 0x20050CE8 0x8FA40030
_L 0x20050CEC 0x8FA50034
_L 0x20050D00 0x8FA40028`

I can savestate now. Could you please test it out too and let me know?

**Comment by jserodio** [comment]
I made some testings but there's not enought improvement to make it to the playable list.
I'm sorry! Closing issue.
