### ISSUE TITLE
Gods Eater Burst

### ISSUE THREAD

**Issue by Risingdawn1** [jserodio/rg351p-ppsspp-settings#4]
Crashes before main menu, on 'wolf' loading screen.

USA+Europe tested.

Latest stable 351elec. Tried various settings. Can't get past loading screen to main menu.

**Comment by jserodio** [comment]
Please try this:
Import the cheats.db, there may be a cheat to fix that.
https://github.com/Saramagrean/CWCheat-Database-Plus-

Download it
https://github.com/Saramagrean/CWCheat-Database-Plus-/raw/master/cheat.db

Place it in your cheats folder.
Then in your game, go to the PPSSPP menu > Cheats > Import from cheats.db

Check if there are any bug fixes available for that game.
Try to fix the framerate to 30.
Force max fps to 30.
Frameskip none.
Scroll down and disable the 60hz mode.

show fps both so you can see the framerate...
Sorry I can't test this game for you right now

If that doesn't work.
Try this settings: https://github.com/jserodio/rg351p-ppsspp-settings/blob/main/settings/THE%203RD%20BIRTHDAY%20(PARASITE%20EVE%203).md

Very important, after you made those changes. Reset the PPSSPP emulator, or LOAD a savestate...
so that the emulator reloads again.
CPU changes only work when you reboot the emulator or load savestates.

Good luck

**Comment by Risingdawn1** [comment]
Fixed: 
I/O Timing Method = Simulate UMD Delays.

Thanks for the response, turns out it was an easy fix.

Except for the I/O timing, game runs 30fps on default settings

**Comment by jserodio** [comment]
Just to let you know, I've credited and fixed the Gods eater entry for other users.
Thanks for collaborating! https://github.com/jserodio/rg351p-ppsspp-settings/wiki/Home/e1164bbe9fe38d59291b3228c43a9a0712736f25#gods-eater-burst
