### ISSUE TITLE
Multiple Games Semi-Playable to Playable

### ISSUE THREAD

**Issue by LanHikari64** [jserodio/rg351p-ppsspp-settings#5]
These are all on default settings.

Games playable upon initial testing:
EXIT
EXIT 2
Holy Invasion of Privacy, Badman, What Did I Do to Deserve This?
What Did I Do to Deserve This, My Lord? 2
ClaDun X2
-------------------------------------------------------------
Games with around 20-30 FPS on initial testing:
NBA Street Showdown
Rainbow Six Vegas
Tony Hawk's Project 8
Tony Hawk's Underground 2 Remix
-------------------------------------------------------------
Unplayable:
Corpse Party

**Comment by jserodio** [comment]
Games playable run at 30 FPS I guess, is there any game playing at 60 out of 60 fps?
Are there any games that originaly plays at 60 fps and we cut down frameskip 1 to make it 30 fps stable?
I understand if that you are playing on default settings, frameskip is auto and 1?
Could you display show fps: Both, that way you may be able to see FPS and Speed percentage.

Thank you so much for your list, I'm adding the playable games as Green (GOOD), and bottom games as (Yellow, almost playable).

**Comment by jserodio** [comment]
Maybe it's time to start using the discussions instead of Issues.
I've made it available in this repository:
https://github.com/jserodio/rg351p-ppsspp-settings/discussions

New game settings can be deposited here:
👾 New games
**Got a game that's almost playable? Ask other users to try their best and find the optimal settings.**
https://github.com/jserodio/rg351p-ppsspp-settings/discussions/categories/new-games
